### ISSUE TITLE
NeumorphicTheme.of(context)!.themeMode = ThemeMode.system; Not working

### ISSUE THREAD

**Issue by sidhu-patil** [gsmlg-dev/Flutter-Neumorphic#2]
NeumorphicRadio(
                  groupValue: groupValue,
                  value: 1,
                  padding: const EdgeInsets.all(12),
                  child: const Text("System Theme"),
                  onChanged: (value) {
                    if (value != null) {
                      setState(() {
                        groupValue = value;
                        NeumorphicTheme.of(context)!.themeMode =
                            ThemeMode.system;
                      });
                    }
                  },
                ),
                
                Theme of app does not change...

**Comment by gsmlg** [comment]
Yes, of course.
